ERROR - 2021-12-22 01:27:24 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-12-22 01:27:24 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 /home/icakshmy/hanaemi/vendor/codeigniter4/framework/system/Database/BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 /home/icakshmy/hanaemi/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /home/icakshmy/hanaemi/vendor/codeigniter4/framework/system/Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 /home/icakshmy/hanaemi/vendor/codeigniter4/framework/system/BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 /home/icakshmy/hanaemi/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(156): CodeIgniter\BaseModel->first()
#5 /home/icakshmy/hanaemi/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#6 /home/icakshmy/hanaemi/vendor/myth/auth/src/Controllers/AuthController.php(88): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#7 /home/icakshmy/hanaemi/vendor/codeigniter4/framework/system/CodeIgniter.php(824): Myth\Auth\Controllers\AuthController->attemptLogin()
#8 /home/icakshmy/hanaemi/vendor/codeigniter4/framework/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 /home/icakshmy/hanaemi/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /home/icakshmy/hanaemi/public/index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2021-12-22 01:27:37 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-12-22 01:27:37 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 /home/icakshmy/hanaemi/vendor/codeigniter4/framework/system/Database/BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 /home/icakshmy/hanaemi/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /home/icakshmy/hanaemi/vendor/codeigniter4/framework/system/Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 /home/icakshmy/hanaemi/vendor/codeigniter4/framework/system/BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 /home/icakshmy/hanaemi/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(156): CodeIgniter\BaseModel->first()
#5 /home/icakshmy/hanaemi/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#6 /home/icakshmy/hanaemi/vendor/myth/auth/src/Controllers/AuthController.php(88): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#7 /home/icakshmy/hanaemi/vendor/codeigniter4/framework/system/CodeIgniter.php(824): Myth\Auth\Controllers\AuthController->attemptLogin()
#8 /home/icakshmy/hanaemi/vendor/codeigniter4/framework/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 /home/icakshmy/hanaemi/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /home/icakshmy/hanaemi/public/index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2021-12-22 01:29:24 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-12-22 01:29:24 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 /home/icakshmy/hanaemi/vendor/codeigniter4/framework/system/Database/BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 /home/icakshmy/hanaemi/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /home/icakshmy/hanaemi/vendor/codeigniter4/framework/system/Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 /home/icakshmy/hanaemi/vendor/codeigniter4/framework/system/BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 /home/icakshmy/hanaemi/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(156): CodeIgniter\BaseModel->first()
#5 /home/icakshmy/hanaemi/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#6 /home/icakshmy/hanaemi/vendor/myth/auth/src/Controllers/AuthController.php(88): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#7 /home/icakshmy/hanaemi/vendor/codeigniter4/framework/system/CodeIgniter.php(824): Myth\Auth\Controllers\AuthController->attemptLogin()
#8 /home/icakshmy/hanaemi/vendor/codeigniter4/framework/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 /home/icakshmy/hanaemi/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /home/icakshmy/hanaemi/public/index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2021-12-22 01:29:55 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-12-22 01:29:55 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 /home/icakshmy/hanaemi/vendor/codeigniter4/framework/system/Database/BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 /home/icakshmy/hanaemi/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /home/icakshmy/hanaemi/vendor/codeigniter4/framework/system/Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 /home/icakshmy/hanaemi/vendor/codeigniter4/framework/system/BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 /home/icakshmy/hanaemi/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(156): CodeIgniter\BaseModel->first()
#5 /home/icakshmy/hanaemi/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#6 /home/icakshmy/hanaemi/vendor/myth/auth/src/Controllers/AuthController.php(88): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#7 /home/icakshmy/hanaemi/vendor/codeigniter4/framework/system/CodeIgniter.php(824): Myth\Auth\Controllers\AuthController->attemptLogin()
#8 /home/icakshmy/hanaemi/vendor/codeigniter4/framework/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 /home/icakshmy/hanaemi/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /home/icakshmy/hanaemi/public/index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2021-12-22 09:38:48 --> Duplicate entry '3-2-1' for key 'id_presensi'
ERROR - 2021-12-22 09:39:03 --> Duplicate entry '3-2-1' for key 'id_presensi'
ERROR - 2021-12-22 09:39:11 --> Duplicate entry '3-2-1' for key 'id_presensi'
ERROR - 2021-12-22 09:39:27 --> Duplicate entry '3-2-1' for key 'id_presensi'
ERROR - 2021-12-22 09:48:37 --> Unknown column 'data_cuti.created_at' in 'order clause'
CRITICAL - 2021-12-22 09:48:37 --> Call to a member function getResult() on bool
#0 /home/icaksh/pemweb/hanae/app/Controllers/User/Presensi.php(24): App\Models\PresensiUserModel->getPresensibyUserId()
#1 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(824): App\Controllers\User\Presensi->index()
#2 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController()
#3 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest()
#4 /home/icaksh/pemweb/hanae/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/home/icaksh/pe...')
#6 {main}
ERROR - 2021-12-22 09:48:38 --> Unknown column 'data_cuti.created_at' in 'order clause'
CRITICAL - 2021-12-22 09:48:38 --> Call to a member function getResult() on bool
#0 /home/icaksh/pemweb/hanae/app/Controllers/User/Presensi.php(24): App\Models\PresensiUserModel->getPresensibyUserId()
#1 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(824): App\Controllers\User\Presensi->index()
#2 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController()
#3 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest()
#4 /home/icaksh/pemweb/hanae/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/home/icaksh/pe...')
#6 {main}
ERROR - 2021-12-22 09:48:38 --> Unknown column 'data_cuti.created_at' in 'order clause'
CRITICAL - 2021-12-22 09:48:38 --> Call to a member function getResult() on bool
#0 /home/icaksh/pemweb/hanae/app/Controllers/User/Presensi.php(24): App\Models\PresensiUserModel->getPresensibyUserId()
#1 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(824): App\Controllers\User\Presensi->index()
#2 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController()
#3 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest()
#4 /home/icaksh/pemweb/hanae/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/home/icaksh/pe...')
#6 {main}
ERROR - 2021-12-22 09:48:39 --> Unknown column 'data_cuti.created_at' in 'order clause'
CRITICAL - 2021-12-22 09:48:39 --> Call to a member function getResult() on bool
#0 /home/icaksh/pemweb/hanae/app/Controllers/User/Presensi.php(24): App\Models\PresensiUserModel->getPresensibyUserId()
#1 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(824): App\Controllers\User\Presensi->index()
#2 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController()
#3 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest()
#4 /home/icaksh/pemweb/hanae/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/home/icaksh/pe...')
#6 {main}
ERROR - 2021-12-22 09:49:05 --> Unknown column 'data_cuti.created_at' in 'order clause'
CRITICAL - 2021-12-22 09:49:05 --> Call to a member function getResult() on bool
#0 /home/icaksh/pemweb/hanae/app/Controllers/User/Presensi.php(24): App\Models\PresensiUserModel->getPresensibyUserId()
#1 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(824): App\Controllers\User\Presensi->index()
#2 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController()
#3 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest()
#4 /home/icaksh/pemweb/hanae/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/home/icaksh/pe...')
#6 {main}
ERROR - 2021-12-22 09:49:06 --> Unknown column 'data_cuti.created_at' in 'order clause'
CRITICAL - 2021-12-22 09:49:06 --> Call to a member function getResult() on bool
#0 /home/icaksh/pemweb/hanae/app/Controllers/User/Presensi.php(24): App\Models\PresensiUserModel->getPresensibyUserId()
#1 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(824): App\Controllers\User\Presensi->index()
#2 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController()
#3 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest()
#4 /home/icaksh/pemweb/hanae/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/home/icaksh/pe...')
#6 {main}
ERROR - 2021-12-22 09:49:06 --> Unknown column 'data_cuti.created_at' in 'order clause'
CRITICAL - 2021-12-22 09:49:06 --> Call to a member function getResult() on bool
#0 /home/icaksh/pemweb/hanae/app/Controllers/User/Presensi.php(24): App\Models\PresensiUserModel->getPresensibyUserId()
#1 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(824): App\Controllers\User\Presensi->index()
#2 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController()
#3 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest()
#4 /home/icaksh/pemweb/hanae/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/home/icaksh/pe...')
#6 {main}
ERROR - 2021-12-22 09:49:34 --> Unknown column 'waktu_masuk.created_at' in 'order clause'
CRITICAL - 2021-12-22 09:49:34 --> Call to a member function getResult() on bool
#0 /home/icaksh/pemweb/hanae/app/Controllers/User/Presensi.php(24): App\Models\PresensiUserModel->getPresensibyUserId()
#1 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(824): App\Controllers\User\Presensi->index()
#2 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController()
#3 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest()
#4 /home/icaksh/pemweb/hanae/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/home/icaksh/pe...')
#6 {main}
ERROR - 2021-12-22 09:49:35 --> Unknown column 'waktu_masuk.created_at' in 'order clause'
CRITICAL - 2021-12-22 09:49:35 --> Call to a member function getResult() on bool
#0 /home/icaksh/pemweb/hanae/app/Controllers/User/Presensi.php(24): App\Models\PresensiUserModel->getPresensibyUserId()
#1 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(824): App\Controllers\User\Presensi->index()
#2 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController()
#3 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest()
#4 /home/icaksh/pemweb/hanae/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/home/icaksh/pe...')
#6 {main}
ERROR - 2021-12-22 10:07:42 --> Duplicate entry '3-2-1' for key 'id_presensi'
CRITICAL - 2021-12-22 10:13:43 --> Function name must be a string
#0 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/View/View.php(214): include()
#1 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/View/View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/Common.php(1097): CodeIgniter\View\View->render()
#3 /home/icaksh/pemweb/hanae/app/Controllers/User/Presensi.php(27): view()
#4 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(824): App\Controllers\User\Presensi->index()
#5 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController()
#6 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest()
#7 /home/icaksh/pemweb/hanae/public/index.php(37): CodeIgniter\CodeIgniter->run()
#8 /home/icaksh/pemweb/hanae/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/home/icaksh/pe...')
#9 {main}
